# =============================================================================
# providers.tf — how this root reaches the cluster
# =============================================================================
# File generated by forge.
#
# This is the only place in the project that knows which cluster an "apply" goes
# to. The module does not know: that is what makes it reusable.
#
# WARNING — without "config_context", the provider uses the CURRENT context of
# the kubeconfig of the machine. Applying in production from a badly positioned
# workstation is the most ordinary accident of this provider; the kube_context
# variable exists to prevent it, do not leave it empty.
# =============================================================================

provider "kubernetes" {
  config_path    = var.kube_config_path
  config_context = var.kube_context
}

# The "random" provider requires no configuration: it calls no
# remote service. The block is declared so that the configuration is readable
# from a single file.
provider "random" {
}

# The "tls" provider requires no configuration: it calls no
# remote service. The block is declared so that the configuration is readable
# from a single file.
provider "tls" {
}
