# =============================================================================
# variables.tf — inputs of the "boutique" module
# =============================================================================
# File generated by forge.
#
# Every variable carries its explanation twice, and that is not a redundancy:
# the comment addresses whoever reads the file, the "description" attribute
# whoever reads "terraform plan", the documentation generated by terraform-docs,
# or the error message of a missing variable.
#
# The variables with no default value are mandatory: Terraform demands them, and
# "-input=false" turns the omission into a clean failure rather than into a
# question left unanswered in a CI log.
# =============================================================================

# Name of the service. Prefixes every created resource and feeds the
# app.kubernetes.io/name label.
variable "service_name" {
  description = "Name of the service. Prefixes every created resource and feeds the app.kubernetes.io/name label."
  type        = string
}

# Name of the environment (dev, staging, prod). Serves as a resource suffix
# and as the value of the app.kubernetes.io/instance label.
variable "environment" {
  description = "Name of the environment (dev, staging, prod). Serves as a resource suffix and as the value of the app.kubernetes.io/instance label."
  type        = string
}

# Targeted Kubernetes namespace. Created by this module if the 'namespace'
# family is retained, assumed to exist otherwise.
variable "namespace" {
  description = "Targeted Kubernetes namespace. Created by this module if the 'namespace' family is retained, assumed to exist otherwise."
  type        = string
}

# Labels applied to every resource, in addition to the app.kubernetes.io
# labels computed by the module.
variable "labels" {
  description = "Labels applied to every resource, in addition to the app.kubernetes.io labels computed by the module."
  type        = map(string)
  default     = {}
}

# Annotations applied to every resource. Leave empty if no controller of the
# cluster expects any.
variable "annotations" {
  description = "Annotations applied to every resource. Leave empty if no controller of the cluster expects any."
  type        = map(string)
  default     = {}
}

# Ceiling of CPU requestable in the namespace, in Kubernetes units (e.g. '4'
# for 4 cores, '500m' for a half).
variable "quota_cpu" {
  description = "Ceiling of CPU requestable in the namespace, in Kubernetes units (e.g. '4' for 4 cores, '500m' for a half)."
  type        = string
  default     = "4"
}

# Ceiling of memory requestable, Kubernetes suffix mandatory (Mi, Gi). A
# bare number would be understood as bytes.
variable "quota_memory" {
  description = "Ceiling of memory requestable, Kubernetes suffix mandatory (Mi, Gi). A bare number would be understood as bytes."
  type        = string
  default     = "8Gi"
}

# Maximum number of simultaneous pods in the namespace.
variable "quota_pods" {
  description = "Maximum number of simultaneous pods in the namespace."
  type        = number
  default     = 30
}

# CPU given to a container that does not request any.
variable "limit_range_default_cpu" {
  description = "CPU given to a container that does not request any."
  type        = string
  default     = "500m"
}

# Memory given to a container that does not request any.
variable "limit_range_default_memory" {
  description = "Memory given to a container that does not request any."
  type        = string
  default     = "512Mi"
}
