{{/*
===============================================================================
_helpers.tpl — naming and labelling functions of the "storefront" chart
===============================================================================
File generated by forge.

No resource name and no label is hardcoded in the templates: everything goes
through the helpers defined here. A single change is therefore enough to rename
or relabel the whole chart.

Naming convention of the helpers:
  storefront.<name>             helper global to the chart
  storefront.<component>.<name> helper specific to a component
===============================================================================
*/}}

{{/*
Name of the chart, possibly replaced by nameOverride.
Truncated to 63 characters: that is the limit of a DNS-1123 label, and a longer
name would be refused by the Kubernetes API.
*/}}
{{- define "storefront.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Full name of the resources: <release>-<chart>.
When the release name already contains the chart name, it is used on its own so
as to avoid duplicates of the "shop-shop" kind.
*/}}
{{- define "storefront.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Identifier of the chart, in the <name>-<version> format, set on the
helm.sh/chart label. The "+" of a possible SemVer build is replaced: it is not
allowed in a label value.
*/}}
{{- define "storefront.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Selection labels: stable and immutable subset of the labels.
They serve as the selector of the Deployments and of the Services; never add a
changing value such as the version to them, on pain of making the Deployment
unmodifiable (the selector field is immutable after creation).
*/}}
{{- define "storefront.selectorLabels" -}}
app.kubernetes.io/name: {{ include "storefront.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Standard labels recommended by Kubernetes, set on every resource.
*/}}
{{- define "storefront.labels" -}}
helm.sh/chart: {{ include "storefront.chart" . }}
{{ include "storefront.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.global.environment }}
environment: {{ .Values.global.environment | quote }}
{{- end }}
{{- end }}

{{/*
-------------------------------------------------------------------------------
Component "api"
-------------------------------------------------------------------------------
*/}}

{{/*
Full name of the resources of the component: <release>-<chart>-api.
*/}}
{{- define "storefront.api.fullname" -}}
{{- printf "%s-%s" (include "storefront.fullname" .) "api" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Selection labels of the component: those of the chart, plus the component label.
*/}}
{{- define "storefront.api.selectorLabels" -}}
{{ include "storefront.selectorLabels" . }}
app.kubernetes.io/component: api
{{- end }}

{{/*
Full labels of the component.
*/}}
{{- define "storefront.api.labels" -}}
{{ include "storefront.labels" . }}
app.kubernetes.io/component: api
{{- end }}

{{/*
Full reference of the image: <registry>/<repository>:<tag>.
A tag left empty in the values falls back on the appVersion of Chart.yaml, which
avoids having to fill it in two places on every release.
*/}}
{{- define "storefront.api.image" -}}
{{- $values := .Values.api -}}
{{- $tag := $values.image.tag | default .Chart.AppVersion -}}
{{- if .Values.global.imageRegistry -}}
{{- printf "%s/%s:%s" .Values.global.imageRegistry $values.image.repository $tag -}}
{{- else -}}
{{- printf "%s:%s" $values.image.repository $tag -}}
{{- end -}}
{{- end }}

{{/*
Name of the ServiceAccount the pods of the component run under.
When the chart creates the account, its name is that of the component; otherwise
it is that of a pre-existing account, and "default" failing that — in which case
the pods inherit the rights shared by the whole namespace.
The workload MUST set serviceAccountName with this helper: without it, the
dedicated account is created but nobody uses it.
*/}}
{{- define "storefront.api.serviceAccountName" -}}
{{- $values := .Values.api -}}
{{- if $values.serviceAccount.create -}}
{{- default (include "storefront.api.fullname" .) $values.serviceAccount.name -}}
{{- else -}}
{{- default "default" $values.serviceAccount.name -}}
{{- end -}}
{{- end }}

{{/*
Name of the ConfigMap of the component. Every resource that references it goes
through this helper: a name copied by hand would end up diverging.
*/}}
{{- define "storefront.api.configMapName" -}}
{{- printf "%s-config" (include "storefront.api.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end }}
