# =============================================================================
# namespace.tf — the partition "boutique" is deployed in
# =============================================================================
# File generated by forge.
#
# Pivot family of the module: every other resource attaches itself to it through
# local.namespace, which is enough to give Terraform the creation order.
#
# WARNING — "terraform destroy" deletes this namespace, and therefore everything
# it contains, including what a Helm chart deployed there and that Terraform does
# not know about. The destruction goes beyond the perimeter of this module.
#
# WARNING — changing the name of the namespace destroys and recreates it:
# Kubernetes does not allow renaming. The plan announces it in one line, without
# warning of what the recreation takes with it.
# =============================================================================

resource "kubernetes_namespace" "this" {
  # "metadata" is a block, not an attribute: that is why the references are
  # written metadata[0].name and not metadata.name.
  metadata {
    name        = var.namespace
    labels      = local.labels
    annotations = var.annotations
  }
}
