# =============================================================================
# quota.tf — budget of the namespace: ResourceQuota and LimitRange
# =============================================================================
# File generated by forge.
#
# CONSEQUENCE TO KNOW ABOUT — as soon as a ResourceQuota covers requests.cpu or
# requests.memory, the API refuses any pod whose container does not declare its
# "resources.requests". The Helm chart of the same service must therefore declare
# them, otherwise the deployment breaks the day this quota is set up, and not
# before.
#
# The LimitRange cushions that risk by giving a default size to the containers
# that do not ask for one — but only to the pods created AFTER it: the pods
# already in place keep their configuration until they restart.
# =============================================================================

resource "kubernetes_resource_quota" "this" {
  metadata {
    name        = "${var.service_name}-quota"
    namespace   = local.namespace
    labels      = local.labels
    annotations = var.annotations
  }

  spec {
    # The same values cap the requests and the limits: a namespace whose sum of
    # limits largely exceeds the sum of requests promises more resources than it
    # has, and eviction arrives under load.
    hard = {
      "requests.cpu"    = var.quota_cpu
      "requests.memory" = var.quota_memory
      "limits.cpu"      = var.quota_cpu
      "limits.memory"   = var.quota_memory
      "pods"            = var.quota_pods
    }
  }
}

resource "kubernetes_limit_range" "this" {
  metadata {
    name        = "${var.service_name}-limits"
    namespace   = local.namespace
    labels      = local.labels
    annotations = var.annotations
  }

  spec {
    limit {
      type = "Container"

      # "default" sets the limit; "default_request" sets the request. Filling in
      # only the first would make the limit be copied into the request, and would
      # reserve far more resources than intended.
      default = {
        cpu    = var.limit_range_default_cpu
        memory = var.limit_range_default_memory
      }

      default_request = {
        cpu    = var.limit_range_default_cpu
        memory = var.limit_range_default_memory
      }
    }
  }
}
