# =============================================================================
# registry_secret.tf — image pull secret for a private registry
# =============================================================================
# File generated by forge.
#
# No credential is written here nor in terraform.tfvars: the password arrives
# through the TF_VAR_registry_password environment variable.
#
# WARNING — the "auth" field of the document is a base64 encoding of the
# user:password pair, not an encryption. Anyone who reads the Terraform state or
# the Kubernetes Secret reads the password. A read-only service account, specific
# to the cluster, is the only reasonable answer.
#
# WARNING — an imagePullSecret only applies in its namespace. A service deployed
# in several namespaces needs one Secret per namespace.
# =============================================================================

resource "kubernetes_secret" "registry" {
  metadata {
    name        = "${var.service_name}-registry"
    namespace   = local.namespace
    labels      = local.labels
    annotations = var.annotations
  }

  # This type imposes the ".dockerconfigjson" key, leading dot included. A bare
  # "auths" key is accepted by the API and rejected by kubelet on the first pull,
  # with an ImagePullBackOff error that does not say why.
  type = "kubernetes.io/dockerconfigjson"

  # "data" receives plain text: the provider encodes it in base64 itself. Passing
  # an already encoded value would double-encode it silently.
  data = {
    ".dockerconfigjson" = jsonencode({
      auths = {
        (var.registry_server) = {
          username = var.registry_username
          password = var.registry_password
          auth     = base64encode("${var.registry_username}:${var.registry_password}")
        }
      }
    })
  }
}
