# =============================================================================
# variables.tf — inputs of the "boutique" module
# =============================================================================
# File generated by forge.
#
# Every variable carries its explanation twice, and that is not a redundancy:
# the comment addresses whoever reads the file, the "description" attribute
# whoever reads "terraform plan", the documentation generated by terraform-docs,
# or the error message of a missing variable.
#
# The variables with no default value are mandatory: Terraform demands them, and
# "-input=false" turns the omission into a clean failure rather than into a
# question left unanswered in a CI log.
# =============================================================================

# Name of the service. Prefixes every created resource and feeds the
# app.kubernetes.io/name label.
variable "service_name" {
  description = "Name of the service. Prefixes every created resource and feeds the app.kubernetes.io/name label."
  type        = string
}

# Name of the environment (dev, staging, prod). Serves as a resource suffix
# and as the value of the app.kubernetes.io/instance label.
variable "environment" {
  description = "Name of the environment (dev, staging, prod). Serves as a resource suffix and as the value of the app.kubernetes.io/instance label."
  type        = string
}

# Targeted Kubernetes namespace. Created by this module if the 'namespace'
# family is retained, assumed to exist otherwise.
variable "namespace" {
  description = "Targeted Kubernetes namespace. Created by this module if the 'namespace' family is retained, assumed to exist otherwise."
  type        = string
}

# Labels applied to every resource, in addition to the app.kubernetes.io
# labels computed by the module.
variable "labels" {
  description = "Labels applied to every resource, in addition to the app.kubernetes.io labels computed by the module."
  type        = map(string)
  default     = {}
}

# Annotations applied to every resource. Leave empty if no controller of the
# cluster expects any.
variable "annotations" {
  description = "Annotations applied to every resource. Leave empty if no controller of the cluster expects any."
  type        = map(string)
  default     = {}
}

# Ceiling of CPU requestable in the namespace, in Kubernetes units (e.g. '4'
# for 4 cores, '500m' for a half).
variable "quota_cpu" {
  description = "Ceiling of CPU requestable in the namespace, in Kubernetes units (e.g. '4' for 4 cores, '500m' for a half)."
  type        = string
  default     = "4"
}

# Ceiling of memory requestable, Kubernetes suffix mandatory (Mi, Gi). A
# bare number would be understood as bytes.
variable "quota_memory" {
  description = "Ceiling of memory requestable, Kubernetes suffix mandatory (Mi, Gi). A bare number would be understood as bytes."
  type        = string
  default     = "8Gi"
}

# Maximum number of simultaneous pods in the namespace.
variable "quota_pods" {
  description = "Maximum number of simultaneous pods in the namespace."
  type        = number
  default     = 30
}

# CPU given to a container that does not request any.
variable "limit_range_default_cpu" {
  description = "CPU given to a container that does not request any."
  type        = string
  default     = "500m"
}

# Memory given to a container that does not request any.
variable "limit_range_default_memory" {
  description = "Memory given to a container that does not request any."
  type        = string
  default     = "512Mi"
}

# Address of the registry. Docker Hub requires the historical form
# https://index.docker.io/v1/ ; the other registries take their bare host
# name.
variable "registry_server" {
  description = "Address of the registry. Docker Hub requires the historical form https://index.docker.io/v1/ ; the other registries take their bare host name."
  type        = string
  default     = "https://index.docker.io/v1/"
}

# Read credential on the registry. Use a read-only service account, never a
# personal account.
variable "registry_username" {
  description = "Read credential on the registry. Use a read-only service account, never a personal account."
  type        = string
  default     = ""
}

# Password or token of the registry. With no default value and absent from
# terraform.tfvars: provide it through TF_VAR_registry_password.
# Secret value: no default value, and absent from terraform.tfvars.
# Provide it through the TF_VAR_registry_password environment variable.
variable "registry_password" {
  description = "Password or token of the registry. With no default value and absent from terraform.tfvars: provide it through TF_VAR_registry_password."
  type        = string
  sensitive   = true
}

# Name of the ServiceAccount. Empty, it is '<service>-deployer'.
variable "service_account_name" {
  description = "Name of the ServiceAccount. Empty, it is '<service>-deployer'."
  type        = string
  default     = ""
}

# Labels of the namespace allowed to reach the service (that of the ingress
# controller). Empty, only the traffic internal to the namespace is allowed.
variable "ingress_namespace_labels" {
  description = "Labels of the namespace allowed to reach the service (that of the ingress controller). Empty, only the traffic internal to the namespace is allowed."
  type        = map(string)
  default     = { "kubernetes.io/metadata.name" = "ingress-nginx" }
}

# Labels of the namespace hosting the DNS service of the cluster. Without
# this opening, no name resolves any more.
variable "dns_namespace_labels" {
  description = "Labels of the namespace hosting the DNS service of the cluster. Without this opening, no name resolves any more."
  type        = map(string)
  default     = { "kubernetes.io/metadata.name" = "kube-system" }
}

# Keys to generate in the Secret (e.g. ['database-password', 'api-token']).
# One random value is produced per key.
variable "generated_secret_keys" {
  description = "Keys to generate in the Secret (e.g. ['database-password', 'api-token']). One random value is produced per key."
  type        = list(string)
  default     = ["password"]
}

# Length of each generated value, in characters.
variable "generated_secret_length" {
  description = "Length of each generated value, in characters."
  type        = number
  default     = 32
}

# Name carried by the certificate (CN). Empty, it is the first name of
# tls_dns_names.
variable "tls_common_name" {
  description = "Name carried by the certificate (CN). Empty, it is the first name of tls_dns_names."
  type        = string
  default     = ""
}

# DNS names covered by the certificate (SAN). Browsers have ignored the CN
# for a long time: it is this list that counts.
variable "tls_dns_names" {
  description = "DNS names covered by the certificate (SAN). Browsers have ignored the CN for a long time: it is this list that counts."
  type        = list(string)
  default     = []
}

# Validity duration of the certificate, in hours (8760 = one year).
variable "tls_validity_hours" {
  description = "Validity duration of the certificate, in hours (8760 = one year)."
  type        = number
  default     = 8760
}

# Delay before expiry from which an apply regenerates the certificate, in
# hours (720 = thirty days).
variable "tls_early_renewal_hours" {
  description = "Delay before expiry from which an apply regenerates the certificate, in hours (720 = thirty days)."
  type        = number
  default     = 720
}
