# =============================================================================
# main.tf — call of the module for the "dev" environment
# =============================================================================
# File generated by forge.
#
# The module is written once and called once per environment: that is what
# guarantees that dev and prod set up the same objects, give or take the values.
# The values themselves are in terraform.tfvars.
#
# Every argument is passed explicitly. Terraform reports loudly an argument the
# module does not declare; it says NOTHING about a variable declared and never
# passed — it simply takes its default value, and the divergence is never seen.
# =============================================================================

module "boutique" {
  source = "../../modules/boutique"

  service_name               = var.service_name
  environment                = var.environment
  namespace                  = var.namespace
  labels                     = var.labels
  annotations                = var.annotations
  quota_cpu                  = var.quota_cpu
  quota_memory               = var.quota_memory
  quota_pods                 = var.quota_pods
  limit_range_default_cpu    = var.limit_range_default_cpu
  limit_range_default_memory = var.limit_range_default_memory
}
