# =============================================================================
# outputs.tf — outputs of the "dev" environment
# =============================================================================
# File generated by forge.
#
# These outputs are the meeting point with the rest of the chain: it is through
#
#   terraform -chdir=environments/dev output -raw namespace
#
# that a pipeline learns where to deploy, rather than copying a naming convention
# that would end up diverging.
# =============================================================================

# Namespace the service is deployed in.
output "namespace" {
  description = "Namespace the service is deployed in."
  value       = module.storefront.namespace
}

# Name of the ResourceQuota set on the namespace.
output "resource_quota_name" {
  description = "Name of the ResourceQuota set on the namespace."
  value       = module.storefront.resource_quota_name
}
