# =============================================================================
# versions.tf — versions required by the "dev" root
# =============================================================================
# File generated by forge.
#
# Every root redeclares its providers: Terraform does not inherit them from the
# called module. The constraints are deliberately identical to those of the
# module — two diverging declarations produce no error, Terraform resolves the
# intersection, and the divergence is only seen the day it becomes empty.
# =============================================================================

terraform {
  required_version = "~> 1.9"

  required_providers {
    # sets up the Kubernetes objects that host the service
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.32"
    }
  }
}
