# =============================================================================
# outputs.tf — what the module returns to its caller
# =============================================================================
# File generated by forge.
#
# The outputs are the contract of the module towards the rest of the chain: it is
# through "terraform output -raw namespace" that a pipeline learns where to
# deploy, without copying a naming convention that could drift.
#
# No output returns a secret value. A generated password stays in the state; the
# module only names the Secret that carries it.
# =============================================================================

# Namespace the service is deployed in.
output "namespace" {
  description = "Namespace the service is deployed in."
  value       = local.namespace
}

# Name of the ResourceQuota set on the namespace.
output "resource_quota_name" {
  description = "Name of the ResourceQuota set on the namespace."
  value       = kubernetes_resource_quota.this.metadata[0].name
}

# Name of the Secret to quote in imagePullSecrets, on the Helm chart side.
output "image_pull_secret_name" {
  description = "Name of the Secret to quote in imagePullSecrets, on the Helm chart side."
  value       = kubernetes_secret.registry.metadata[0].name
}

# Name of the deployment ServiceAccount.
output "service_account_name" {
  description = "Name of the deployment ServiceAccount."
  value       = kubernetes_service_account.deployer.metadata[0].name
}

# Name of the Secret carrying the generated values. Its value is not exposed
# as an output.
output "generated_secret_name" {
  description = "Name of the Secret carrying the generated values. Its value is not exposed as an output."
  value       = kubernetes_secret.generated.metadata[0].name
}

# Name of the kubernetes.io/tls Secret to quote in the Ingress.
output "tls_secret_name" {
  description = "Name of the kubernetes.io/tls Secret to quote in the Ingress."
  value       = kubernetes_secret.tls.metadata[0].name
}
