# =============================================================================
# service_account.tf — deployment identity of the service
# =============================================================================
# File generated by forge.
#
# Gives the deployment chain an identity specific to the namespace, with the
# rights of a "helm upgrade" and nothing more. No cluster-scoped right: a Role
# only applies in its namespace, and that is intended.
#
# WARNING — since Kubernetes 1.24, no token Secret is created automatically for a
# ServiceAccount. To obtain a token, prefer "kubectl create token" (short-lived,
# revocable token) to a durable Secret of type
# kubernetes.io/service-account-token.
# =============================================================================

resource "kubernetes_service_account" "deployer" {
  metadata {
    name        = local.service_account_name
    namespace   = local.namespace
    labels      = local.labels
    annotations = var.annotations
  }
}

resource "kubernetes_role" "deployer" {
  metadata {
    name        = local.service_account_name
    namespace   = local.namespace
    labels      = local.labels
    annotations = var.annotations
  }

  # Objects of the "core" API group (api_groups = [""]).
  rule {
    api_groups = [""]
    resources  = ["configmaps", "persistentvolumeclaims", "pods", "secrets", "serviceaccounts", "services"]
    verbs      = ["get", "list", "watch", "create", "update", "patch", "delete"]
  }

  # Workloads.
  rule {
    api_groups = ["apps"]
    resources  = ["daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs      = ["get", "list", "watch", "create", "update", "patch", "delete"]
  }

  # Scheduled tasks.
  rule {
    api_groups = ["batch"]
    resources  = ["cronjobs", "jobs"]
    verbs      = ["get", "list", "watch", "create", "update", "patch", "delete"]
  }

  # Network exposure.
  rule {
    api_groups = ["networking.k8s.io"]
    resources  = ["ingresses", "networkpolicies"]
    verbs      = ["get", "list", "watch", "create", "update", "patch", "delete"]
  }

  # Scaling and availability.
  rule {
    api_groups = ["autoscaling", "policy"]
    resources  = ["horizontalpodautoscalers", "poddisruptionbudgets"]
    verbs      = ["get", "list", "watch", "create", "update", "patch", "delete"]
  }
}

resource "kubernetes_role_binding" "deployer" {
  metadata {
    name        = local.service_account_name
    namespace   = local.namespace
    labels      = local.labels
    annotations = var.annotations
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "Role"
    name      = kubernetes_role.deployer.metadata[0].name
  }

  # The API group of a ServiceAccount subject is the empty string. It is
  # rbac.authorization.k8s.io that applies for a User or a Group: the opposite is
  # accepted by Terraform and rejected by the API at apply time.
  subject {
    api_group = ""
    kind      = "ServiceAccount"
    name      = kubernetes_service_account.deployer.metadata[0].name
    namespace = local.namespace
  }
}
