# =============================================================================
# versions.tf — versions required by the "boutique" module
# =============================================================================
# File generated by forge.
#
# A module declares the versions it needs; it never configures a provider. It is
# the calling root — environments/<env>/providers.tf — that decides which cluster
# is targeted. A "provider" block written here would make the module unusable
# elsewhere.
# =============================================================================

terraform {
  # Upper bound mandatory: an open constraint would let a future major version of
  # Terraform break this module without anything having been changed.
  required_version = "~> 1.9"

  required_providers {
    # sets up the Kubernetes objects that host the service
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.32"
    }

    # generates the passwords, never written in the specification
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }

    # builds the self-signed certificates of the working environments
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}
