# =============================================================================
# outputs.tf — what the module returns to its caller
# =============================================================================
# File generated by forge.
#
# The outputs are the contract of the module towards the rest of the chain: it is
# through "terraform output -raw namespace" that a pipeline learns where to
# deploy, without copying a naming convention that could drift.
#
# No output returns a secret value. A generated password stays in the state; the
# module only names the Secret that carries it.
# =============================================================================

# Namespace the service is deployed in.
output "namespace" {
  description = "Namespace the service is deployed in."
  value       = local.namespace
}

# Name of the ResourceQuota set on the namespace.
output "resource_quota_name" {
  description = "Name of the ResourceQuota set on the namespace."
  value       = kubernetes_resource_quota.this.metadata[0].name
}
