"""Resource families of the Terraform domain.

One family = one `.tf` file of the module, the resources it declares, the
variables it adds and the traps it avoids. This is the only domain knowledge of
the plugin: the core does not know what a namespace is.

The **traps** are not decoration. Each one explains a choice in the generated
code that would look arbitrary without it -- why a quota imposes `requests` on
the Helm chart, why a NetworkPolicy has to open DNS, why a password generated by
Terraform makes encrypting the state mandatory. They are displayed by
`forge catalog terraform <family>` and taken up as comments in the generated
files.

No invented resource: every type quoted exists in the announced provider.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from forge.plugins.terraform.enums import ResourceFamily
from forge.plugins.terraform.variables import Variable, optional, required


@dataclass(frozen=True)
class Family:
    """A resource family, retained by the specification or not."""

    #: Identifier used in `terraform.resources` of forge.yml.
    name: str

    #: One-line summary.
    summary: str

    #: Long description, displayed by `forge catalog terraform <family>`.
    details: str

    #: Terraform resource types declared by the file of the family.
    resources: tuple[str, ...]

    #: Local names of the providers it depends on.
    providers: tuple[str, ...]

    #: Input variables it adds to the module.
    variables: tuple[Variable, ...] = ()

    #: Module outputs it adds: name -> description.
    outputs: dict[str, str] = field(default_factory=dict)

    #: Measured traps, displayed and taken up as comments.
    traps: tuple[str, ...] = ()

    def option_descriptions(self) -> dict[str, str]:
        """Variables of the family, in the format `CatalogEntry` expects."""
        return {variable.name: variable.description for variable in self.variables}


#: Traps common to every resource of the Kubernetes provider: they hold for each
#: family, and repeating them in every one would be noise.
PROVIDER_TRAPS: tuple[str, ...] = (
    "In the kubernetes provider, `metadata` is a **list** block: one writes "
    "`metadata[0].name`, never `metadata.name`. The second form passes "
    "validation and fails at plan time.",
    "Without `config_context`, the provider uses the *current* context of the "
    "kubeconfig of the machine: applying in production from a badly positioned "
    "workstation is the most ordinary accident of this provider.",
)


FAMILIES: tuple[Family, ...] = (
    Family(
        name=ResourceFamily.NAMESPACE.value,
        summary="Creates the namespace the service is deployed in",
        details=(
            "Sets up the partition itself, with the app.kubernetes.io labels of "
            "the service. This is the pivot family: the others attach themselves "
            "to it by reference, which gives Terraform the creation order with "
            "no explicit depends_on.\n\n"
            "Absent, the module assumes the namespace already created by the "
            "platform team and merely attaches itself to it by its name."
        ),
        resources=("kubernetes_namespace",),
        providers=("kubernetes",),
        outputs={"namespace": "Name of the namespace, created or taken up."},
        traps=(
            "`terraform destroy` deletes the namespace, and therefore "
            "**everything** it contains -- including what a Helm chart deployed "
            "there and that Terraform does not know about. The destruction goes "
            "beyond the perimeter.",
            "Changing the name of the namespace destroys and recreates it "
            "(ForceNew behaviour): the content is lost, with no warning other "
            "than the plan line.",
            "A namespace being deleted stays in the Terminating phase as long as "
            "a finalizer has not given back control; Terraform waits, and the "
            "wait looks like a hang.",
        ),
    ),
    Family(
        name=ResourceFamily.QUOTA.value,
        summary="ResourceQuota and LimitRange: the budget of the namespace",
        details=(
            "Caps what the namespace can consume and gives a default size to the "
            "containers that do not declare one.\n\n"
            "This is the family that has the most effect on the other domains: "
            "as soon as a ResourceQuota covers cpu or memory, the API refuses any "
            "pod whose container has no `resources.requests`."
        ),
        resources=("kubernetes_resource_quota", "kubernetes_limit_range"),
        providers=("kubernetes",),
        variables=(
            optional(
                "quota_cpu",
                "string",
                "Ceiling of CPU requestable in the namespace, in Kubernetes "
                "units (e.g. '4' for 4 cores, '500m' for a half).",
                "4",
                per_environment=True,
            ),
            optional(
                "quota_memory",
                "string",
                "Ceiling of memory requestable, Kubernetes suffix mandatory "
                "(Mi, Gi). A bare number would be understood as bytes.",
                "8Gi",
                per_environment=True,
            ),
            optional(
                "quota_pods",
                "number",
                "Maximum number of simultaneous pods in the namespace.",
                30,
                per_environment=True,
            ),
            optional(
                "limit_range_default_cpu",
                "string",
                "CPU given to a container that does not request any.",
                "500m",
            ),
            optional(
                "limit_range_default_memory",
                "string",
                "Memory given to a container that does not request any.",
                "512Mi",
            ),
        ),
        outputs={"resource_quota_name": "Name of the ResourceQuota set on the namespace."},
        traps=(
            "As soon as a quota covers `requests.cpu` or `requests.memory`, "
            "**every** pod without `resources.requests` is refused at admission. "
            "The Helm chart of the same service must therefore declare its "
            "requests, otherwise the deployment breaks the day the quota is set "
            "up.",
            "The LimitRange only applies to the pods **created after** it: the "
            "pods already in place keep their configuration, and the divergence "
            "is only seen at the next restart.",
            "A quota reduced below the current consumption evicts nothing: it "
            "only blocks the subsequent creations. The namespace looks healthy "
            "until the next deployment.",
        ),
    ),
    Family(
        name=ResourceFamily.REGISTRY_SECRET.value,
        summary="Image pull secret for a private registry",
        details=(
            "Sets up a `kubernetes.io/dockerconfigjson` Secret that the pods "
            "reference in `imagePullSecrets`. The credentials are **never** "
            "written in the specification nor in the generated files: they arrive "
            "through TF_VAR_registry_password."
        ),
        resources=("kubernetes_secret",),
        providers=("kubernetes",),
        variables=(
            optional(
                "registry_server",
                "string",
                "Address of the registry. Docker Hub requires the historical "
                "form https://index.docker.io/v1/ ; the other registries take "
                "their bare host name.",
                "https://index.docker.io/v1/",
            ),
            optional(
                "registry_username",
                "string",
                "Read credential on the registry. Use a read-only service "
                "account, never a personal account.",
                "",
            ),
            required(
                "registry_password",
                "string",
                "Password or token of the registry. With no default value and "
                "absent from terraform.tfvars: provide it through "
                "TF_VAR_registry_password.",
                sensitive=True,
            ),
        ),
        outputs={
            "image_pull_secret_name": (
                "Name of the Secret to quote in imagePullSecrets, on the Helm chart side."
            )
        },
        traps=(
            "The key of the Secret must be exactly `.dockerconfigjson`, leading "
            "dot included, and the value a complete `{\"auths\": {...}}` "
            "document. A bare `auths` key is accepted by Terraform and rejected "
            "by kubelet on the first pull.",
            "The provider encodes `data` in base64 itself; passing an already "
            "encoded value there double-encodes it silently. It is `data`, not "
            "`binary_data`, that receives plain text.",
            "The `auth` field of the document is the `user:password` pair in "
            "base64 -- an encoding, not an encryption. Anyone who reads the "
            "Terraform state or the Secret reads the password.",
            "An imagePullSecret only applies in its namespace: a service deployed "
            "in several namespaces needs one Secret per namespace.",
        ),
    ),
    Family(
        name=ResourceFamily.SERVICE_ACCOUNT.value,
        summary="ServiceAccount, Role and RoleBinding for the deployments",
        details=(
            "Gives the deployment chain an identity of its own in the namespace, "
            "with the rights strictly necessary to a `helm upgrade`: read and "
            "write the application objects, nothing more. No cluster-scoped right "
            "is granted."
        ),
        resources=(
            "kubernetes_service_account",
            "kubernetes_role",
            "kubernetes_role_binding",
        ),
        providers=("kubernetes",),
        variables=(
            optional(
                "service_account_name",
                "string",
                "Name of the ServiceAccount. Empty, it is '<service>-deployer'.",
                "",
            ),
        ),
        outputs={
            "service_account_name": "Name of the deployment ServiceAccount.",
        },
        traps=(
            "Since Kubernetes 1.24, no token Secret is created automatically for "
            "a ServiceAccount: `default_secret_name` is empty. A durable token "
            "requires a `kubernetes.io/service-account-token` Secret declared "
            "explicitly -- prefer a short-lived token obtained through "
            "`kubectl create token`.",
            "In a RoleBinding `subject`, a ServiceAccount wants "
            "`api_group = \"\"`; it is `rbac.authorization.k8s.io` that holds for "
            "a User or a Group. The opposite is accepted by Terraform and "
            "rejected by the API at apply time.",
            "A Role only applies in its namespace. The cluster-scoped objects -- "
            "CustomResourceDefinition, StorageClass -- will stay inaccessible, "
            "which is intended.",
        ),
    ),
    Family(
        name=ResourceFamily.NETWORK_POLICY.value,
        summary="Closes the namespace by default, and reopens the strict minimum",
        details=(
            "Sets up a deny-by-default policy on the whole namespace, then "
            "reopens that without which nothing works: DNS resolution, and the "
            "incoming traffic coming from the namespace of the ingress "
            "controller.\n\n"
            "Without a network plugin that applies them (Calico, Cilium, Antrea), "
            "a NetworkPolicy is accepted by the API and **without any effect**: "
            "the namespace looks protected and is not."
        ),
        resources=("kubernetes_network_policy",),
        providers=("kubernetes",),
        variables=(
            optional(
                "ingress_namespace_labels",
                "map(string)",
                "Labels of the namespace allowed to reach the service (that of "
                "the ingress controller). Empty, only the traffic internal to "
                "the namespace is allowed.",
                {"kubernetes.io/metadata.name": "ingress-nginx"},
            ),
            optional(
                "dns_namespace_labels",
                "map(string)",
                "Labels of the namespace hosting the DNS service of the cluster. "
                "Without this opening, no name resolves any more.",
                {"kubernetes.io/metadata.name": "kube-system"},
            ),
        ),
        outputs={},
        traps=(
            "A deny-by-default policy with no egress rule towards DNS (port 53, "
            "UDP **and** TCP) breaks all name resolution in the namespace. The "
            "outage presents itself as application slowness, not as a network "
            "problem.",
            "An empty `pod_selector {}` selects **every** pod of the namespace. "
            "That is exactly what is wanted for a deny-by-default, and exactly "
            "what is not wanted in an opening rule.",
            "In a `from` rule, `namespace_selector` and `pod_selector` in the "
            "**same** block form an AND; in two separate blocks, an OR. The "
            "difference between the two is a far wider opening than intended, and "
            "nothing reports it.",
            "The kubelet probes come from the node, not from a pod: an ingress "
            "rule that is too strict makes the probes fail and restarts the "
            "service in a loop.",
        ),
    ),
    Family(
        name=ResourceFamily.RANDOM_SECRET.value,
        summary="Generated passwords, deposited as a Secret",
        details=(
            "Generates one password per requested key and deposits them in a "
            "single Secret. No secret value enters forge.yml nor any generated "
            "file: that is the point of the family."
        ),
        resources=("random_password", "kubernetes_secret"),
        providers=("random", "kubernetes"),
        variables=(
            optional(
                "generated_secret_keys",
                "list(string)",
                "Keys to generate in the Secret (e.g. ['database-password', "
                "'api-token']). One random value is produced per key.",
                ["password"],
            ),
            optional(
                "generated_secret_length",
                "number",
                "Length of each generated value, in characters.",
                32,
            ),
        ),
        outputs={
            "generated_secret_name": (
                "Name of the Secret carrying the generated values. Its value is "
                "not exposed as an output."
            )
        },
        traps=(
            "`random_password` keeps the value **in plain text in the Terraform "
            "state**. The state backend must therefore be encrypted and its "
            "access restricted: the password is no more secret than the state.",
            "Without `keepers`, the value never changes -- which is the intended "
            "behaviour, but forbids any rotation. Rotating a password requires "
            "modifying a keeper, not destroying the resource.",
            "`random_password` produces by default special characters that break "
            "connection URLs (`@`, `/`, `:`). Hence the restricted "
            "`override_special` in the generated code.",
            "The service that reads this Secret does not reread it on its own: a "
            "Secret mounted as a volume is refreshed with a delay, a Secret "
            "injected as an environment variable is **never** refreshed before a "
            "restart.",
        ),
    ),
    Family(
        name=ResourceFamily.TLS_CERTIFICATE.value,
        summary="Self-signed certificate of the working environments",
        details=(
            "Builds a private key and a self-signed certificate, deposited as a "
            "`kubernetes.io/tls` Secret ready to be referenced by an Ingress.\n\n"
            "**For working environments only.** In production, a self-signed "
            "certificate is refused by any serious client: use cert-manager or a "
            "certificate issued by a recognised authority. The generated code "
            "recalls it in a comment."
        ),
        resources=("tls_private_key", "tls_self_signed_cert", "kubernetes_secret"),
        providers=("tls", "kubernetes"),
        variables=(
            optional(
                "tls_common_name",
                "string",
                "Name carried by the certificate (CN). Empty, it is the first "
                "name of tls_dns_names.",
                "",
                per_environment=True,
            ),
            optional(
                "tls_dns_names",
                "list(string)",
                "DNS names covered by the certificate (SAN). Browsers have "
                "ignored the CN for a long time: it is this list that counts.",
                [],
                per_environment=True,
            ),
            optional(
                "tls_validity_hours",
                "number",
                "Validity duration of the certificate, in hours (8760 = one year).",
                8760,
            ),
            optional(
                "tls_early_renewal_hours",
                "number",
                "Delay before expiry from which an apply regenerates the "
                "certificate, in hours (720 = thirty days).",
                720,
            ),
        ),
        outputs={
            "tls_secret_name": "Name of the kubernetes.io/tls Secret to quote in the Ingress."
        },
        traps=(
            "The certificate expires without reporting anything: Terraform only "
            "regenerates it on the next apply, and only if "
            "`early_renewal_hours` is reached. A project applied twice a year "
            "with a one-year certificate breaks down.",
            "The private key is stored **in plain text in the state**, like any "
            "resource of the tls provider.",
            "Browsers have ignored the Common Name since 2017: a certificate "
            "without `dns_names` matching the host is refused, whatever its CN.",
            "A `kubernetes.io/tls` Secret requires exactly the two keys "
            "`tls.crt` and `tls.key`. Any other naming is accepted by the API and "
            "ignored by the ingress controller.",
        ),
    ),
)

#: Families indexed by name.
BY_NAME: dict[str, Family] = {family.name: family for family in FAMILIES}
