# =============================================================================
# outputs.tf — outputs of the "prod" environment
# =============================================================================
# File generated by forge.
#
# These outputs are the meeting point with the rest of the chain: it is through
#
#   terraform -chdir=environments/prod output -raw namespace
#
# that a pipeline learns where to deploy, rather than copying a naming convention
# that would end up diverging.
# =============================================================================

# Namespace the service is deployed in.
output "namespace" {
  description = "Namespace the service is deployed in."
  value       = module.storefront.namespace
}

# Name of the ResourceQuota set on the namespace.
output "resource_quota_name" {
  description = "Name of the ResourceQuota set on the namespace."
  value       = module.storefront.resource_quota_name
}

# Name of the Secret to quote in imagePullSecrets, on the Helm chart side.
output "image_pull_secret_name" {
  description = "Name of the Secret to quote in imagePullSecrets, on the Helm chart side."
  value       = module.storefront.image_pull_secret_name
}

# Name of the deployment ServiceAccount.
output "service_account_name" {
  description = "Name of the deployment ServiceAccount."
  value       = module.storefront.service_account_name
}

# Name of the Secret carrying the generated values. Its value is not exposed
# as an output.
output "generated_secret_name" {
  description = "Name of the Secret carrying the generated values. Its value is not exposed as an output."
  value       = module.storefront.generated_secret_name
}

# Name of the kubernetes.io/tls Secret to quote in the Ingress.
output "tls_secret_name" {
  description = "Name of the kubernetes.io/tls Secret to quote in the Ingress."
  value       = module.storefront.tls_secret_name
}
