# =============================================================================
# locals.tf — values computed once for the whole module
# =============================================================================
# File generated by forge.
# =============================================================================

locals {
  # The namespace is read from the resource rather than from the variable, and
  # that is deliberate: this reference gives Terraform the creation order.
  # Everything that uses local.namespace therefore waits for the creation of the
  # namespace, without any depends_on having to write it.
  namespace = kubernetes_namespace.this.metadata[0].name

  # Labels applied to every resource. The first four are the labels recommended
  # by Kubernetes; the Helm charts of the same service set the same ones, which
  # makes it possible to find with a single "kubectl get -l" everything that
  # belongs to the service, whatever the tool that set it up.
  labels = merge({
    "app.kubernetes.io/name"       = var.service_name
    "app.kubernetes.io/instance"   = "${var.service_name}-${var.environment}"
    "app.kubernetes.io/part-of"    = var.service_name
    "app.kubernetes.io/managed-by" = "terraform"
  }, var.labels)

  # Name of the deployment ServiceAccount. Left empty in the variables, it is
  # deduced from the name of the service: a predictable default name is worth
  # more than a value to fill in for every environment.
  service_account_name = var.service_account_name != "" ? var.service_account_name : "${var.service_name}-deployer"

  # Common Name of the certificate. Browsers have ignored it since 2017 — it is
  # the dns_names list that is authoritative — but a certificate with no CN is
  # refused by certain old libraries.
  tls_common_name = var.tls_common_name != "" ? var.tls_common_name : (length(var.tls_dns_names) > 0 ? var.tls_dns_names[0] : var.service_name)
}
