# =============================================================================
# network_policy.tf — the namespace is closed, then reopened to the strict
# minimum
# =============================================================================
# File generated by forge.
#
# WARNING — without a network plugin that applies them (Calico, Cilium, Antrea),
# a NetworkPolicy is accepted by the API and stays WITHOUT ANY EFFECT. The
# namespace looks protected and is not. Check the CNI of the cluster before
# relying on this file.
#
# WARNING — a deny-by-default policy with no opening towards DNS breaks all name
# resolution in the namespace. The outage presents itself as application
# slowness, never as a network problem: hence the first egress rule below, which
# is not optional.
# =============================================================================

resource "kubernetes_network_policy" "default_deny" {
  metadata {
    name        = "${var.service_name}-default-deny"
    namespace   = local.namespace
    labels      = local.labels
    annotations = var.annotations
  }

  spec {
    # An empty pod_selector selects ALL the pods of the namespace. That is
    # exactly what is wanted here, and exactly what must not be written in an
    # opening rule.
    pod_selector {
    }

    policy_types = ["Ingress", "Egress"]

    # DNS resolution. Both protocols are necessary: UDP for the common queries,
    # TCP for the answers too large for a datagram.
    egress {
      ports {
        port     = "53"
        protocol = "UDP"
      }

      ports {
        port     = "53"
        protocol = "TCP"
      }

      to {
        namespace_selector {
          match_labels = var.dns_namespace_labels
        }
      }
    }

    # Outgoing traffic towards the other pods of the same namespace.
    egress {
      to {
        pod_selector {
        }
      }
    }

    # Incoming traffic coming from the other pods of the same namespace.
    ingress {
      from {
        pod_selector {
        }
      }
    }
  }
}

resource "kubernetes_network_policy" "allow_ingress_controller" {
  # No opening rule if no ingress namespace is designated: the service then stays
  # reachable from its own namespace only.
  count = length(var.ingress_namespace_labels) > 0 ? 1 : 0

  metadata {
    name        = "${var.service_name}-allow-ingress"
    namespace   = local.namespace
    labels      = local.labels
    annotations = var.annotations
  }

  spec {
    pod_selector {
      match_labels = {
        "app.kubernetes.io/name" = var.service_name
      }
    }

    policy_types = ["Ingress"]

    # namespace_selector alone, in its own "from" block: adding a pod_selector in
    # the SAME block would form an AND, in a separate block an OR. The difference
    # between the two is a far wider opening than intended, and nothing reports
    # it.
    ingress {
      from {
        namespace_selector {
          match_labels = var.ingress_namespace_labels
        }
      }
    }
  }
}
