# =============================================================================
# .tflint.hcl — rules applied by tflint
# =============================================================================
# File generated by forge.
#
# tflint sees what "terraform validate" lets through: a missing provider version
# constraint, a variable declared and never used, a resource name outside the
# convention. The two tools are complementary, neither replaces the other.
#
# The "terraform" rule set is built into tflint: no "tflint --init" is necessary,
# and the validation works with no network access.
# =============================================================================

config {
  # Local modules are inspected, not those of the registry: inspecting the latter
  # would require downloading them, and therefore network access, in order to
  # report defects that are not ours.
  call_module_type = "local"
}

plugin "terraform" {
  enabled = true
  preset  = "recommended"
}
