# =============================================================================
# backend.tf — where the state of the "prod" environment is kept
# =============================================================================
# File generated by forge.
#
# The Terraform state carries IN PLAIN TEXT everything the resources expose,
# including the generated passwords. The choice of the backend is therefore a
# security choice before being a convenience choice.
#
# The state key is specific to this environment: two roots sharing a state would
# destroy each other on the first "apply", and nothing in Terraform announces it
# in advance.
#
# No secret value here. The credentials to access the storage are passed at
# initialisation time:
#
#   terraform init -backend-config="access_key=..."
#
# or by the environment variables of the provider (AWS_ACCESS_KEY_ID,
# GOOGLE_CREDENTIALS, ARM_CLIENT_SECRET...).
# =============================================================================

terraform {
  backend "s3" {
    bucket  = "etats-terraform-plateforme"
    encrypt = "true"
    key     = "boutique/prod/terraform.tfstate"
    region  = "eu-west-3"
  }
}
