# =============================================================================
# terraform.tfvars — values of the "prod" environment
# =============================================================================
# File generated by forge, loaded automatically by Terraform.
#
# NO SECRET VALUE HERE, and that is not an oversight: a file of this name ends up
# versioned. The secret variables have no default value and are provided through
# TF_VAR_<name> — the CI pulls them from its vault, never from the repository.
#
# Any variable declared in variables.tf can be added here, even those forge has
# not pre-filled. A variable that is NOT declared, on the other hand, makes
# Terraform fail: this file is not a place to note down parameters.
#
# PRODUCTION environment.
# =============================================================================

service_name = "storefront"
environment  = "prod"
namespace    = "storefront-prod"
labels       = { tier = "frontend" }
kube_context = "plateforme-prod"
quota_cpu    = "4"
quota_memory = "8Gi"
quota_pods   = 30
