# =============================================================================
# variables.tf — inputs of the "prod" root
# =============================================================================
# File generated by forge.
#
# These variables take up those of the module, plus what concerns the access to
# the cluster. The values of this environment are in terraform.tfvars; any
# non-secret variable can be overridden there, even those forge has not
# pre-filled.
#
# The secret variables have no default value and do not appear in
# terraform.tfvars: they are provided through TF_VAR_<name>.
# =============================================================================

# Path of the kubeconfig file used to reach the cluster. Specific to the
# machine: leave the default value and override it through
# TF_VAR_kube_config_path if needed.
variable "kube_config_path" {
  description = "Path of the kubeconfig file used to reach the cluster. Specific to the machine: leave the default value and override it through TF_VAR_kube_config_path if needed."
  type        = string
  default     = "~/.kube/config"
}

# Targeted kubeconfig context. Never leave it empty: with no explicit
# context, Terraform applies on the current context of the machine, whatever
# it is.
variable "kube_context" {
  description = "Targeted kubeconfig context. Never leave it empty: with no explicit context, Terraform applies on the current context of the machine, whatever it is."
  type        = string
  default     = ""
}

# Name of the service. Prefixes every created resource and feeds the
# app.kubernetes.io/name label.
variable "service_name" {
  description = "Name of the service. Prefixes every created resource and feeds the app.kubernetes.io/name label."
  type        = string
}

# Name of the environment (dev, staging, prod). Serves as a resource suffix
# and as the value of the app.kubernetes.io/instance label.
variable "environment" {
  description = "Name of the environment (dev, staging, prod). Serves as a resource suffix and as the value of the app.kubernetes.io/instance label."
  type        = string
}

# Targeted Kubernetes namespace. Created by this module if the 'namespace'
# family is retained, assumed to exist otherwise.
variable "namespace" {
  description = "Targeted Kubernetes namespace. Created by this module if the 'namespace' family is retained, assumed to exist otherwise."
  type        = string
}

# Labels applied to every resource, in addition to the app.kubernetes.io
# labels computed by the module.
variable "labels" {
  description = "Labels applied to every resource, in addition to the app.kubernetes.io labels computed by the module."
  type        = map(string)
  default     = {}
}

# Annotations applied to every resource. Leave empty if no controller of the
# cluster expects any.
variable "annotations" {
  description = "Annotations applied to every resource. Leave empty if no controller of the cluster expects any."
  type        = map(string)
  default     = {}
}

# Ceiling of CPU requestable in the namespace, in Kubernetes units (e.g. '4'
# for 4 cores, '500m' for a half).
variable "quota_cpu" {
  description = "Ceiling of CPU requestable in the namespace, in Kubernetes units (e.g. '4' for 4 cores, '500m' for a half)."
  type        = string
  default     = "4"
}

# Ceiling of memory requestable, Kubernetes suffix mandatory (Mi, Gi). A
# bare number would be understood as bytes.
variable "quota_memory" {
  description = "Ceiling of memory requestable, Kubernetes suffix mandatory (Mi, Gi). A bare number would be understood as bytes."
  type        = string
  default     = "8Gi"
}

# Maximum number of simultaneous pods in the namespace.
variable "quota_pods" {
  description = "Maximum number of simultaneous pods in the namespace."
  type        = number
  default     = 30
}

# CPU given to a container that does not request any.
variable "limit_range_default_cpu" {
  description = "CPU given to a container that does not request any."
  type        = string
  default     = "500m"
}

# Memory given to a container that does not request any.
variable "limit_range_default_memory" {
  description = "Memory given to a container that does not request any."
  type        = string
  default     = "512Mi"
}
