# =============================================================================
# main.tf — call of the module for the "dev" environment
# =============================================================================
# File generated by forge.
#
# The module is written once and called once per environment: that is what
# guarantees that dev and prod set up the same objects, give or take the values.
# The values themselves are in terraform.tfvars.
#
# Every argument is passed explicitly. Terraform reports loudly an argument the
# module does not declare; it says NOTHING about a variable declared and never
# passed — it simply takes its default value, and the divergence is never seen.
# =============================================================================

module "storefront" {
  source = "../../modules/storefront"

  service_name               = var.service_name
  environment                = var.environment
  namespace                  = var.namespace
  labels                     = var.labels
  annotations                = var.annotations
  quota_cpu                  = var.quota_cpu
  quota_memory               = var.quota_memory
  quota_pods                 = var.quota_pods
  limit_range_default_cpu    = var.limit_range_default_cpu
  limit_range_default_memory = var.limit_range_default_memory
  registry_server            = var.registry_server
  registry_username          = var.registry_username
  registry_password          = var.registry_password
  service_account_name       = var.service_account_name
  ingress_namespace_labels   = var.ingress_namespace_labels
  dns_namespace_labels       = var.dns_namespace_labels
  generated_secret_keys      = var.generated_secret_keys
  generated_secret_length    = var.generated_secret_length
  tls_common_name            = var.tls_common_name
  tls_dns_names              = var.tls_dns_names
  tls_validity_hours         = var.tls_validity_hours
  tls_early_renewal_hours    = var.tls_early_renewal_hours
}
