# =============================================================================
# tls_certificate.tf — self-signed certificate of the working environments
# =============================================================================
# File generated by forge.
#
# FOR WORKING ENVIRONMENTS ONLY. In production, a self-signed certificate is
# refused by any serious client: use cert-manager, or a certificate issued by a
# recognised authority.
#
# WARNING — this certificate expires without reporting anything. Terraform only
# regenerates it on the next "apply", and only if early_renewal_hours is reached.
# A project applied twice a year with a one-year certificate breaks down on a day
# when nobody changed anything.
#
# WARNING — the private key is stored in plain text in the Terraform state, like
# any resource of the tls provider.
# =============================================================================

resource "tls_private_key" "this" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "tls_self_signed_cert" "this" {
  private_key_pem = tls_private_key.this.private_key_pem

  subject {
    common_name  = local.tls_common_name
    organization = var.service_name
  }

  # It is these names that browsers check; the Common Name has been ignored since
  # 2017. An empty list produces a certificate that nothing will accept.
  dns_names = var.tls_dns_names

  validity_period_hours = var.tls_validity_hours
  early_renewal_hours   = var.tls_early_renewal_hours

  allowed_uses = [
    "digital_signature",
    "key_encipherment",
    "server_auth",
  ]
}

resource "kubernetes_secret" "tls" {
  metadata {
    name        = "${var.service_name}-tls"
    namespace   = local.namespace
    labels      = local.labels
    annotations = var.annotations
  }

  # This type requires exactly the two keys tls.crt and tls.key. Any other naming
  # is accepted by the API and ignored by the ingress controller, which will then
  # serve its default certificate without saying so.
  type = "kubernetes.io/tls"

  data = {
    "tls.crt" = tls_self_signed_cert.this.cert_pem
    "tls.key" = tls_private_key.this.private_key_pem
  }
}
