# =============================================================================
# random_secret.tf — generated passwords, deposited as a Secret
# =============================================================================
# File generated by forge.
#
# No secret value enters forge.yml nor any generated file: these values only
# exist once applied. That is the whole point of the family.
#
# WARNING — random_password keeps the value IN PLAIN TEXT in the Terraform
# state. The password is no more secret than the state: an encrypted backend with
# restricted access is a precondition, not an improvement.
#
# WARNING — the service that reads this Secret does not reread it on its own.
# Mounted as a volume, it is refreshed with a delay; injected as an environment
# variable, it is NEVER refreshed before a restart of the pod.
# =============================================================================

resource "random_password" "generated" {
  for_each = toset(var.generated_secret_keys)

  length = var.generated_secret_length

  # Special characters restricted: @ / : ? # break the connection URLs of the
  # postgres://user:password@host/database kind, and the diagnosis is long
  # because the failure looks like an authentication error.
  special          = true
  override_special = "-_=+."

  # Without keepers, the value never changes — intended behaviour, but one that
  # forbids any rotation. Rotating a password consists in modifying a keeper,
  # never in destroying the resource.
  keepers = {
    environment = var.environment
  }
}

resource "kubernetes_secret" "generated" {
  metadata {
    name        = "${var.service_name}-generated"
    namespace   = local.namespace
    labels      = local.labels
    annotations = var.annotations
  }

  type = "Opaque"

  data = { for cle, motdepasse in random_password.generated : cle => motdepasse.result }
}
